version: '3'

volumes:
  postgres_data:

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      -  ./:/code/
    ports:
      - 127.0.0.1:8180:8080
    depends_on:
      - postgres
    restart: always
    networks:
      - default

  postgres:
    image: postgres:15.4-alpine
    environment:
      PAGER: less
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5455:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default
