"""memes

Revision ID: 5eee8e7593a1
Revises:
Create Date: 2024-01-13 21:53:53.228600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5eee8e7593a1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "gender")
    op.add_column("userdevice", sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, "userdevice", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userdevice", type_="foreignkey")
    op.drop_column("userdevice", "user_id")
    op.add_column(
        "user",
        sa.Column("gender", postgresql.ENUM("MALE", "FEMALE", name="gender"), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
