"""init-2

Revision ID: 6c2cb85e79bb
Revises: 4326b390ef0c
Create Date: 2023-12-17 16:49:28.147445

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c2cb85e79bb"
down_revision: Union[str, None] = "4326b390ef0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.alter_column(
        "user",
        "date_of_birth",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=True,
    )
    op.drop_index("ix_user_uuid", table_name="user")
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.drop_column("user", "uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.create_index("ix_user_uuid", "user", ["uuid"], unique=False)
    op.alter_column(
        "user",
        "date_of_birth",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_column("user", "id")
    # ### end Alembic commands ###
