"""indexes for memehistory

Revision ID: 9173b12178b8
Revises: d21059b91552
Create Date: 2024-01-14 02:22:17.961891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9173b12178b8"
down_revision: Union[str, None] = "d21059b91552"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_memehistory_meme_id"), "memehistory", ["meme_id"], unique=False)
    op.create_index(op.f("ix_memehistory_user_id"), "memehistory", ["user_id"], unique=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_memehistory_user_id"), table_name="memehistory")
    op.drop_index(op.f("ix_memehistory_meme_id"), table_name="memehistory")
    # ### end Alembic commands ###
