"""init-3

Revision ID: f9337c273ebb
Revises: 6c2cb85e79bb
Create Date: 2023-12-17 16:50:39.718607

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f9337c273ebb"
down_revision: Union[str, None] = "6c2cb85e79bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_id", table_name="user")
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    # ### end Alembic commands ###
